
package com.mycompany.losatuendos.Vista;

import SistemaFacade.SistemaFacade;
import javax.swing.JOptionPane;


/**
 *
 * @author jhona
 */
public class Login extends javax.swing.JFrame {
    
       
    private SistemaFacade facade;
    /**
     * Creates new form Login
     */
    public Login(SistemaFacade facade) {
        this.facade = facade;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_nombreCompañia = new javax.swing.JLabel();
        Label_Resume = new javax.swing.JLabel();
        Label_contrasena = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        label_correo = new javax.swing.JLabel();
        jButton_inicio = new javax.swing.JButton();
        jPasswordField_contrasena = new javax.swing.JPasswordField();
        Label_contrasena1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Label_nombreCompañia.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Label_nombreCompañia.setForeground(new java.awt.Color(51, 51, 51));
        Label_nombreCompañia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_nombreCompañia.setText("Los Atuendos");

        Label_Resume.setBackground(new java.awt.Color(255, 0, 255));
        Label_Resume.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Label_Resume.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        Label_Resume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Resume.setText("Gestion de inventario y alquiler");

        Label_contrasena.setBackground(new java.awt.Color(102, 102, 102));
        Label_contrasena.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_contrasena.setForeground(new java.awt.Color(153, 153, 153));
        Label_contrasena.setText("Contraseña");

        jTextField_correo.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_correo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTextField_correo.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jTextField_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correoActionPerformed(evt);
            }
        });

        label_correo.setBackground(new java.awt.Color(102, 102, 102));
        label_correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_correo.setForeground(new java.awt.Color(153, 153, 153));
        label_correo.setText("Correo Electrónico");

        jButton_inicio.setBackground(new java.awt.Color(0, 102, 255));
        jButton_inicio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton_inicio.setForeground(new java.awt.Color(255, 255, 255));
        jButton_inicio.setText("Iniciar Sesión");
        jButton_inicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inicioActionPerformed(evt);
            }
        });

        jPasswordField_contrasena.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_contrasena.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"), 1, true));

        Label_contrasena1.setBackground(new java.awt.Color(255, 255, 255));
        Label_contrasena1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_contrasena1.setForeground(new java.awt.Color(0, 102, 255));
        Label_contrasena1.setText("¿Necesitas registrarte?");
        Label_contrasena1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_contrasena1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_contrasena1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atuendo64x64.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_nombreCompañia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_Resume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_contrasena1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Label_contrasena)
                                .addComponent(label_correo)
                                .addComponent(jButton_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField_contrasena))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_nombreCompañia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Resume)
                .addGap(59, 59, 59)
                .addComponent(label_correo)
                .addGap(18, 18, 18)
                .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Label_contrasena)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_contrasena1)
                .addGap(18, 18, 18)
                .addComponent(jButton_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correoActionPerformed

    private void jButton_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inicioActionPerformed
        String correo = jTextField_correo.getText().trim();
        String password = new String(jPasswordField_contrasena.getPassword());

        if (correo.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese correo y contraseña.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean loginOk = facade.login(correo, password);

        if (loginOk) {
            Dashboard vistaDashboard = new Dashboard(facade);
            vistaDashboard.pack();
            vistaDashboard.setLocationRelativeTo(null);
            vistaDashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos. Intente de nuevo.", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_inicioActionPerformed

    private void Label_contrasena1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_contrasena1MouseClicked
        RegistroEmpleados registroEmpleados = new RegistroEmpleados(facade);
        registroEmpleados.setVisible(true);
        registroEmpleados.pack();
        registroEmpleados.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Label_contrasena1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Resume;
    private javax.swing.JLabel Label_contrasena;
    private javax.swing.JLabel Label_contrasena1;
    private javax.swing.JLabel Label_nombreCompañia;
    private javax.swing.JButton jButton_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_contrasena;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JLabel label_correo;
    // End of variables declaration//GEN-END:variables
}
